# Mod Loading Info
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

# VillageCraft2 Essentials Config
[[mods]]
modId="villagecraft2essentials"
version="${mod_version}"
displayName="${mod_name}"
logoFile="villagecraft2essentials.png"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

# Dependency for Forge
[[dependencies.villagecraft2essentials]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

# Dependency for Minecraft
[[dependencies.villagecraft2essentials]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"




