# Mod Loading Info
modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="All rights reserved"

# VillageCraft2 Essentials Config
[[mods]]
modId="villagecraft2essentials"
version="${file.jarVersion}"
displayName="VillageCraft2 Essentials"
logoFile="villagecraft2essentials.png"
credits="Created TardisEngineer from Timeship Modding"
authors="TardisEngineer"
description='''
Work in progress!
'''

# Dependency for Forge
[[dependencies.villagecraft2essentials]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

# Dependency for Minecraft
[[dependencies.villagecraft2essentials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
